version: "3"
services:
  codimd:
    image: linuxserver/codimd:arm32v7-latest
    restart: unless-stopped
    volumes:
      - codimd_data:/config
    environment:
      - DB_HOST=qnap.panxonia.ge.org.es
      - DB_USER=codimd
      - DB_PASS=${CODIMD_MYSQL_PASSWORD}
      - DB_NAME=codimd
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Madrid
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes: 
  codimd_data:
