version: '3.4'

services:
  mysql:
    image: hypriot/rpi-mysql
    ports:
      - 3306:3306
    environment: 
      - MYSQL_DATABASE=blackpearldb
      - MYSQL_USER=pirate
      - MYSQL_PASSWORD=hypriot
      - MYSQL_ROOT_PASSWORD=secret
    volumes: 
      - blackpearldb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  blackpearldb_data:
